import Header from "@/app/conponents/header/Header";
import "../../globalcss/globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Footer from "@/app/conponents/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="jp">
      <Head>
        <title>skillPark</title>
        <meta
          name="description"
          content="SkillPark is a web application that supports everyone's smooth skill acquisition."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
